=== jochenw/qse/qse-is-core/src/main/resources/com/github/jochenw/qse/is/core/rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://namespaces.github.com/jochenw/qse/is/rules/1.0.0" xmlns:tns="http://namespaces.github.com/jochenw/qse/is/rules/1.0.0" elementFormDefault="qualified">
  <xs:element name="rules">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="rule" type="tns:TRule" minOccurs="0" maxOccurs="unbounded">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="TRule">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="property">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="listProperty">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="value" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string"/>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:choice>
    <xs:attribute name="enabled" type="xs:boolean" use="optional" default="true"/>
    <xs:attribute name="class" type="xs:string" use="required"/>
    <xs:attribute name="severity" type="tns:TSeverity" use="optional" default="WARN"/>
    <xs:attribute name="id" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="TRuleProperty">
    <xs:choice>
      <xs:element name="property">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="listProperty">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
          <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:complexType>

  <xs:simpleType name="TSeverity">
    <xs:restriction base="xs:string">
      <xs:enumeration value="INFO"/>
      <xs:enumeration value="WARN"/>
      <xs:enumeration value="ERROR"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== jochenw/qse/qse-is-core/src/main/resources/com/github/jochenw/qse/is/core/rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<rules xmlns="http://namespaces.github.com/jochenw/qse/is/rules/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://namespaces.github.com/jochenw/qse/is/rules/1.0.0 rules.xsd ">
  <rule enabled="true" class="com.github.jochenw.qse.is.core.rules.PipelineDebugRule" severity="ERROR">
    <property name="permittedValues">0,1</property>
  </rule>
  <rule enabled="true" id="DebugLogRule" class="com.github.jochenw.qse.is.core.rules.ForbiddenServicesRule" severity="ERROR">
    <listProperty name="serviceNames">
      <value>pub.flow:debugLog</value>
    </listProperty>
  </rule>
  <rule enabled="true" id="AppendToListRule" class="com.github.jochenw.qse.is.core.rules.ForbiddenServicesRule" severity="WARN">
    <listProperty name="serviceNames">
      <value>pub.list:appendToDocumentList</value>
      <value>pub.list:appendToStringList</value>
    </listProperty>
  </rule>
  <rule enabled="true" class="com.github.jochenw.qse.is.core.rules.LogMessageCatalogRule" severity="ERROR">
    <property name="sourceService">wx.log.pub:logMessageFromCatalogDev</property>
    <property name="targetService">wx.log.pub:logMessageFromCatalog</property>
    <property name="severitySpecificationSeverity">WARN</property>
  </rule>
  <rule enabled="true" class="com.github.jochenw.qse.is.core.rules.AuditSettingsRule" severity="ERROR">
    <!-- The first values configure, which audit settings we are expected for the services given below. In all cases, we may  -->
    <!-- either configure the single numerical value (default severity), or an explicit severity, as in "ERROR:1". -->
    <property name="expectedEnableAuditingValue">1</property><!-- 0=Never, 1=Always, 2=When top-level service only -->
    <property name="expectedLogOnValue">0</property><!-- 0=Error only, 1=Error, and success, 2=Error, success, and start -->
    <property name="expectedIncludePipelineValue">1</property><!-- 0=Never, 1=On errors only, 2=Always -->
    <!-- In what follows, we configure, which services are being checked. -->
    <listProperty name="includedServices">
      <!-- Public servives (located below "pub" -->
      <value>^.*\.pub(\..*\:|\:).*$</value>
      <!-- Web servives (located below "ws.provider" -->
      <value>^.*\.ws\.provider(\..*\:|\:).*$</value>
      <!-- REST servives (named _get, _post, _put, or _delete) -->
      <value>^.*\:(_get|_post|_put|_delete)$</value>
    </listProperty>
    <listProperty name="excludedServices">
      <!-- Nothing to exclude -->
    </listProperty>
  </rule>
</rules>
