=== jochenw/qse/qse-lin-core/src/main/resources/com/github/jochenw/qse/lin/core/api/qse-lin-plugins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 
      Copyright 2019 Jochen Wiedmann
 
   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://namespaces.github.com/jochenw/qse/lin/core/plugins/1.0.0" xmlns:tns="http://namespaces.github.com/jochenw/qse/lin/core/plugins/1.0.0" elementFormDefault="qualified">
  <xs:element name="qse-lin-plugins">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="plugin" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="description" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string"/>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="property" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="name" type="xs:string" use="required"/>
                      <xs:attribute name="value" type="xs:string" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="name" type="xs:string" use="optional"/>
            <xs:attribute name="class" type="xs:string" use="optional"/>
            <xs:attribute name="familyId" type="xs:string" use="optional"/>
            <xs:attribute name="override" type="xs:string" use="optional" default="false"/>
            <xs:attribute name="type" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="family"/>
                  <xs:enumeration value="license"/>
                  <xs:enumeration value="matcher"/>
                  <xs:enumeration value="archive"/>
                  <xs:enumeration value="exclusion"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jochenw/qse/qse-lin-core/src/main/resources/META-INF/qse/lin/qse-lin-plugins.xml
<?xml version="1.0" encoding="UTF-8"?>
<qse-lin-plugins xmlns="http://namespaces.github.com/jochenw/qse/lin/core/plugins/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://namespaces.github.com/jochenw/qse/lin/core/plugins/1.0.0 ../../com/github/jochenw/qse/lin/core/api/qse-lin-plugins.xsd ">
  <plugin type="family" id="ASLV2" name="Apache License, Version 2">
    <description>
      The Apache License is recognised by the Open Source Initiative as a popular and widely deployed licence with a
      strong community. All of The Apache Software Foundation’s projects, including the Apache HTTP Server project
      whose software powers more than half of the Internet’s web servers, use this licence. Consequently the licence
      is widely deployed even though it is used by only about two percent of the open source-licensed projects on
      the software repository Sourceforge. It is an interesting licence to compare with the Berkeley Software
      Distribution (BSD) licence, which it resembles in some ways.
      The license itself can be read at http://www.opensource.org/licenses/apache2.0.php.
    </description>
  </plugin>
  <plugin type="license" id="Apache-2.0" familyId="ASLV2" name="Apache License, Version 2"/>
  <plugin type="matcher" class="com.github.jochenw.qse.lin.core.plugins.PatternBasedMatcher" id="Apache-2.0">
    <property name="patterns">Licensed under the Apache License, Version 2.0 (the "License")&#10;http://www.apache.org/licenses/LICENSE-2.0</property>
  </plugin>

  <!--  The GNU General Public License, version 3 -->
  <plugin type="family" id="GPLV3" name="GNU General Public License, Version 3">
    <description>
      The GNU General Public License v3 (GPL v3 for short) is the next version of the extremely popular free and open
      source licence the GPL v2. It updates its predecessor to reflect the changes that have taken place in the IT
      world over the sixteen years that separate them.
      The licence itself can be read at http://www.opensource.org/licenses/GPL-3.0.
    </description>
  </plugin>
  <plugin type="license" id="GPL-3.0" familyId="GPLV3" name="GNU General Public License, Version 3"/>
  <plugin type="matcher" class="com.github.jochenw.qse.lin.core.plugins.FullTextMatcher" id="GPL-3.0">
    <property name="text1">
      This program is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.
    </property>
  </plugin>

  <!--  The GNU General Public License, version 2 -->
  <plugin type="family" id="GPLV2" name="GNU General Public License, Version 2">
    <description>
      The GNU General Public License v2 .(GPL v2 for short) is the most commonly used open source licence. Approximately
      70% of the projects in the software repository Sourceforge use the GPL v2. The licence itself can be read at
      http://www.opensource.org/licenses/gpl-license.php.
    </description>
  </plugin>
  <plugin type="license" id="GPL-2.0" familyId="GPLV2" name="GNU General Public License, Version 2"/>
  <plugin type="matcher" class="com.github.jochenw.qse.lin.core.plugins.FullTextMatcher" id="GPL-2.0">
    <property name="text1">
      This program is free software; you can redistribute it and/or
      modify it under the terms of the GNU General Public License
      as published by the Free Software Foundation; either version 2
      of the License, or (at your option) any later version."
    </property>
  </plugin>

  <!-- The GNU General Public License, version 1 -->
  <plugin type="family" id="GPLV1" name="GNU General Public License, Version 1">
    <description>
      The GNU General Public License v1 .(GPL v1 for short) is the most commonly used open source license. Approximately
      70% of the projects in the software repository Sourceforge use the GPL v2. The license itself can be read at
      http://www.opensource.org/licenses/gpl-license.php.
    </description>
  </plugin>

  <plugin type="license" id="GPL-1.0" familyId="GPLV1" name="GNU General Public License, Version 1"/>
  <plugin type="matcher" class="com.github.jochenw.qse.lin.core.plugins.FullTextMatcher" id="GPL-1.0">
    <property name="text1">
       This program is free software; you can redistribute it and/or modify
       it under the terms of the GNU General Public License as published by
       the Free Software Foundation; either version 1, or (at your option)
       any later version.
    </property>
  </plugin>

  <!-- The MIT License -->
  <plugin type="family" id="MIT" name="The MIT License">
    <description>
      The MIT License is a permissive free software license originating
      at the Massachusetts Institute of Technology (MIT). As a
      permissive license, it puts only very limited restriction
      on reuse and has, therefore, an excellent license compatibility.
      The MIT license permits reuse within proprietary software
      provided that all copies of the licensed software include
      a copy of the MIT License terms and the copyright notice.
      The MIT license is also compatible with many copyleft licenses,
      such as the GNU General Public License (GPL);
      MIT licensed software can be integrated into GPL software,
      but not the other way around.
    </description>
  </plugin>
  <plugin type="license" id="MIT" familyId="MIT" name="The MIT License"/>
  <plugin type="matcher" class="com.github.jochenw.qse.lin.core.plugins.FullTextMatcher" id="MIT">
    <property name="text1">
      Permission is hereby granted, free of charge, to any person
      obtaining a copy of this software and associated documentation
      files (the "Software"), to deal in the Software without
      restriction, including without limitation the rights to use,
      copy, modify, merge, publish, distribute, sublicense,
      and/or sell copies of the Software, and to permit persons
      to whom the Software is furnished to do so, subject to the
      following conditions:
    </property>
    <property name="text2">
      The above copyright notice and this permission notice shall
      be included in all copies or substantial portions of the
      Software.
    </property>
    <property name="text3">
      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
      KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
      WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
      PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
      OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
      OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
      OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
      THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
    </property>
  </plugin>

  <!--  The OASIS License  -->
  <plugin type="family" id="OASIS" name="OASIS Open License">
    <description>
      The OASIS Open License.
    </description>
  </plugin>
  <plugin type="license" id="OASIS" familyId="OASIS" name="OASIS Open License"/>
  <plugin type="matcher" class="com.github.jochenw.qse.lin.core.plugins.FullTextMatcher" id="OASIS">
    <property name="copyright">.*Copyright\s.*OASIS Open.*\s*</property>
    <property name="text1">
      This document and translations of it may be copied and furnished to
      others and derivative works that comment on or otherwise explain it
      or assist in its implementation may be prepared copied published and
      distributed.
    </property>
  </plugin>

  <!-- The Modified BSD License Family -->
  <plugin type="family" id="BSD-2-Clause" name="Modified BSD License">
    <description>
      This license allows unlimited redistribution for any purpose as
      long as its copyright notices and the license's disclaimers of
      warranty are maintained. The license also contains a clause
      restricting use of the names of contributors for endorsement
      of a derived work without specific permission.
    </description>
  </plugin>

  <!--  The TMF854 License -->
  <plugin type="license" id="TMF854" familyId="BSD-2-Clause" name="TeleManagement Forum License"/>
  <plugin type="matcher" class="com.github.jochenw.qse.lin.core.plugins.FullTextMatcher" id="TMF854">
    <property name="copyright">\s*TMF854 Version 1.0 - Copyright TeleManagement Forum\s*</property>
  </plugin>

  <!--  QSE Lin internal licenses: NOTC, and BIN -->
  <plugin type="family" id="QLIN" name="QSE Lin internal Pseudo Licenses">
    <description>
      There is a set of "pseudo licenses", which are reserved for QSE Lin's internal purposes. These
      dummy licenses include the "Notice License" (Matching files are assumed to be notice files,
      thus ignorable.) and the "Binary License" (Matching files are assumed to be binaries, thus
      ignorable.)
    </description>
  </plugin>
  <plugin type="license" id="NOTC" familyId="QLIN" name="QSE Lin internal Notice License"/>
  <plugin type="license" id="BIN" familyId="QLIN" name="QSE Lin internal Binary License"/>
  <plugin type="matcher" class="com.github.jochenw.qse.lin.core.plugins.NameExtensionMatcher" id="NOTC" name="QSE Lin Notice Matcher">
    <property name="caseSensitive">false</property>
    <property name="extensions">txt</property>
  </plugin>
  <plugin type="matcher" class="com.github.jochenw.qse.lin.core.plugins.NamePatternMatcher" id="NOTC" name="QSE Lin Notice Pattern Matcher">
    <property name="caseSensitive">true</property>
    <property name="patterns">NOTICE*&#10;LICENSE*&#10;README*</property>
  </plugin>
  <plugin type="matcher" class="com.github.jochenw.qse.lin.core.plugins.NameExtensionMatcher" id="BIN" name="QSE Lin Binary Matcher">
    <property name="caseSensitive">false</property>
    <property name="extensions">jar zip 7z gif jpg jpeg</property>
  </plugin>
  <!-- Javadoc files -->
